config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
  }

  resources :users, only: :show
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  root to:"posts#index"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.create(post_id: params[:post_id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.haml
-if user_signed_in?
  -if current_user.already_liked?(post)
    %button.btn.btn
      .d-flex.form-inline.justify-content-center
        = link_to post_like_path(post,post.id),class:"already-heart-btn ml-4" ,method: :delete ,remote: true do
          =icon("fa","heart")
        .heart-count.ml-3
          =post.likes.count
  -else
    %button.btn.btn
      .d-flex.form-inline.justify-content-center
        = link_to post_likes_path(post) ,class:"heart-btn ml-4" ,method: :post ,remote: true do
          = icon("fa","heart")
        .heart-count.ml-3
          =post.likes.count
-else
  -# %button.btn.btn
  -#   .d-flex.form-inline.justify-content-center
  -#     = link_to post_likes_path(post) ,class:"heart-btn ml-4" ,method: :post ,remote: true do
  -#       = icon("fa","heart")
  -#     .heart-count.ml-3
  -#       =post.likes.count
  %button.btn.btn
    .d-flex.form-inline.justify-content-center
      = icon("fa","heart")
      .heart-count.ml-3
        =post.likes.count

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");