config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
  }

  resources :users, only: :show
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  root to:"posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts ,dependent: :destroy
  has_many :likes ,dependent: :destroy
  has_many :liked_posts ,through: :likes, source: :post
  has_many :comments

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @likes = @user.likes
    @comments = @user.comments

    # if params[:q]
    #   @q = Post.ransack(params[:q])
    #   @posts = @q.result(distinct: true).page(params[:page])
    # end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.haml
%head

-# post===============================================
.container.col-10.mt-4
  .title-box.d-flex.justify-content-between
    %h2 POST
    %h4.d-flex
      =@posts.count
      post
  %table.table
    %thead.thead.bg-success.text-white
      %tr
        %th
          No.
        %th
          store name
        %th
          review
        %th
          score
        %th
          post time
        %th.text-center
          link
    %tbody
    -@posts.each.with_index do |post,index|
      %tr.bg-white
        %th
          = index+1
        %th
          = post.name
          %td
            = post.review
          %td
            = post.score
          %td
            = post.created_at.strftime('%y/%-m/%-d (%a) %H:%M')
          %td.text-center
            .btn-group
              %button.btn.btn-success
                = link_to post_path(post) do
                  =icon("fa","info-circle",class:"card-btn")
              %button.btn.btn-success
                = link_to edit_post_path(post) do
                  =icon("fa","edit",class:"card-btn")
              %button.btn.btn-success
                = link_to post_path(post),method: :delete ,data: {confirm: "「#{post.name}」を削除していいですか ?"} do
                  =icon("fa","trash-alt",class:"card-btn")

-# likes===============================================
.container.col-10.mt-4
  .title-box.d-flex.justify-content-between
    %h2 LIKE
    %h4.d-flex
      =@likes.count
      like
  %table.table
    %thead.thead.bg-warning.text-white
      %tr
        %th
          No.
        %th
          store name
        %th
          review
        %th
          score
        %th
          post time
        %th.text-center
          link
    %tbody
    -@likes.each.with_index do |like,index|
      %tr.bg-white
        %th
          = index+1
        %th
          = like.post.name
          %td
            = like.post.review
          %td
            = like.post.score
          %td
            = like.post.created_at.strftime('%y/%-m/%-d (%a) %H:%M')
          %td.text-center
            .btn-group
              %button.btn.btn-warning
                = link_to post_path(like.post) do
                  =icon("fa","info-circle",class:"card-btn")

-# comment===============================================
.container.col-10.mt-4
  .title-box.d-flex.justify-content-between
    %h2 COMMENT
    %h4.d-flex
      =@comments.count
      comment
  %table.table
    %thead.thead.bg-primary.text-white
      %tr
        %th
          No.
        %th
          store name
        %th
          comment
        %th
          comment time
        %th.text-center
          link
    %tbody
    -@comments.each.with_index do |comment,index|
      %tr.bg-white
        %th
          = index+1
        %th
          = comment.post.name
          %td
            = comment.text
          %td
            = comment.created_at.strftime('%y/%-m/%-d (%a) %H:%M')
          %td.text-center
            .btn-group
              %button.btn.btn-primary
                = link_to post_path(comment.post) do
                  =icon("fa","info-circle",class:"card-btn")
              %button.btn.btn-primary
                = link_to post_comment_path(comment,comment.id),method: :delete ,data: {confirm: "「#{comment.text}」を削除していいですか ?"} do
                  =icon("fa","trash-alt",class:"card-btn")